// <auto-generated />
using System;
using LeaveService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeaveService.Migrations
{
    [DbContext(typeof(LeaveDbContext))]
    partial class LeaveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeaveService.Models.LeaveRequest", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid?>("ApprovedBy").HasColumnType("uuid");
                b.Property<DateTime?>("ApprovedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("EndDate").HasColumnType("timestamp with time zone");
                b.Property<Guid>("EmployeeId").HasColumnType("uuid");
                b.Property<string>("EmployeeName").IsRequired().HasColumnType("text");
                b.Property<string>("LeaveType").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<Guid>("ManagerId").HasColumnType("uuid");
                b.Property<int>("NumberOfDays").HasColumnType("integer");
                b.Property<string>("Reason").IsRequired().HasColumnType("text");
                b.Property<string>("RejectionReason").HasColumnType("text");
                b.Property<DateTime>("StartDate").HasColumnType("timestamp with time zone");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("EmployeeId");
                b.HasIndex("ManagerId");
                b.HasIndex("Status");
                b.ToTable("LeaveRequests");
            });
#pragma warning restore 612, 618
        }
    }
}
