// <auto-generated />
using System;
using EmployeeService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmployeeService.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeService.Models.Employee", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Department").IsRequired().HasColumnType("text");
                b.Property<string>("Designation").IsRequired().HasColumnType("text");
                b.Property<string>("Email").IsRequired().HasColumnType("text");
                b.Property<string>("FullName").IsRequired().HasColumnType("text");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<DateTime>("JoinDate").HasColumnType("timestamp with time zone");
                b.Property<Guid>("ManagerId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Employees");
            });

            modelBuilder.Entity("EmployeeService.Models.LeaveBalance", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("EmployeeId").HasColumnType("uuid");
                b.Property<string>("LeaveType").IsRequired().HasColumnType("text");
                b.Property<int>("TotalAllocated").HasColumnType("integer");
                b.Property<int>("UsedDays").HasColumnType("integer");
                b.Property<int>("Year").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("EmployeeId", "LeaveType", "Year").IsUnique();
                b.ToTable("LeaveBalances");
                b.HasOne("EmployeeService.Models.Employee", "Employee")
                    .WithMany("LeaveBalances")
                    .HasForeignKey("EmployeeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
